### ISSUE TITLE
Replace panics with errors, catch remaining panics at library boundary

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#11]
Remove panics from the core protocol implementation, and instead return errors.

**Comment by Kubuxu** [comment]
There are still some panics left over.

**Comment by anorth** [comment]
Can we talk about this? There are now some places in the code where a panic/error is reflecting an internal invariant violation. The f3 state is inconsistent and it cannot be used. As a library, I can understand why panic might never be the right answer, but the noise of the error handling is significant.

At the moment, opaque errors give the library user no ability to distinguish between "this message is bad" and "my internal state is so broken, you must start over". If we don't want to use a panic for that, let's design some more thoughtful error types. But until we do, I think replacing the panic in those cases is counter productive: it's more noise and will make it harder to identify those internal assertions properly later on.

**Comment by Stebalien** [comment]
One option is to have internal panics and catch them at the top. But they had better not be forwarded to lotus.

**Comment by ranchalp** [comment]
I actually do agree with this. I will replace the errors that reflect an internal invariant violation with panics for now.

**Comment by anorth** [comment]
A bunch of discussion went into PR #59 instead of here. I will try to summarise it and then contribute.

@Stebalien:
- You can't crash the entire application (I agree)
- There needs to be a recovery path. You have to try very hard to recover before giving up (I disagree)
- Even if granite stops working, lotus can still continue validating the main chain (without finality) (I agree)

So firstly, if go-f3 panics (except for the trivial already-checked indexing issues), then we must catch those panics at the entry points so that it does not propagate to the client. I am going to claim that go-f3 should have such panics (that "should never happen") and so we should add such recovery.

It is also essential that the error returned to Lotus from that recovery is clearly distinguished from other errors, e.g. of invalid messages. This error must signal that the f3 state is invalid and it is unsafe to continue execution of this instance. This is a big difference from most errors which mean "that message was bad, but my internal state is fine so gimme another one".

@Stebalien appeals to "security" as justification for why there should be extensive recovery attempts:
> If everyone just gives up on a round if there's a single bug, that's makes that bug a potential attack vector.

I appeal to security as justification why there should not. The panics we are talking about are internal invariant violations. Our state does not say what we think it says, our code does not do what we think it does. We essentially have no idea what the state means; we were wrong at least once. Continuing the protocol with such state is _more_ dangerous than stopping, because it could lead to, e.g. finalising the wrong thing. Every point that doesn't give up after noticing an internal invariant violation is a potential attack vector to make the protocol _decide the wrong thing_, rather than just not decide.

The commit https://github.com/filecoin-project/go-f3/pull/59/commits/c62c9d687a3e721598545a0456aba6c30e277630 added error returns to the `beginPhase` methods which are rooted in internal state invariant violations. In this case in fact I think there is a good chance that we can refactor the state to make the error go away. So maybe we can defer the need to panic a bit longer.

**Comment by Stebalien** [comment]
> I appeal to security as justification why there should not. The panics we are talking about are internal invariant violations. Our state does not say what we think it says, our code does not do what we think it does. We essentially have no idea what the state means; we were wrong at least once. Continuing the protocol with such state is more dangerous than stopping, because it could lead to, e.g. finalising the wrong thing. Every point that doesn't give up after noticing an internal invariant violation is a potential attack vector to make the protocol decide the wrong thing, rather than just not decide.

Yeah, you're right. F3 is supposed to be "safety over liveness" and we still have the longest-chain protocol which is "liveness over safety".

But can we somehow discard the current instance instead of just stopping? Or would that still be a safety issue?

> So firstly, if go-f3 panics (except for the trivial already-checked indexing issues), then we must catch those panics at the entry points so that it does not propagate to the client. I am going to claim that go-f3 should have such panics (that "should never happen") and so we should add such recovery.

Fair enough. We need to catch panics anyways, so we might as well panic.

> It is also essential that the error returned to Lotus from that recovery is clearly distinguished from other errors, e.g. of invalid messages. This error must signal that the f3 state is invalid and it is unsafe to continue execution of this instance. This is a big difference from most errors which mean "that message was bad, but my internal state is fine so gimme another one".

I'm not sure what lotus would do in this case other than log...

**Comment by Stebalien** [comment]
Ah, well, I guess it could raise an alert (without having the F3 library understand what lotus "alerts" are).

**Comment by ranchalp** [comment]
> But can we somehow discard the current instance instead of just stopping? Or would that still be a safety issue?

Discarding an instance halts f3. F3 does not start a new instance until the previous one has been terminated (with a decision that is). If the decision is Abort, then agreement must be reached upon the base chain, and for that, Granite must not panic or have some sort of unexpected error.

**Comment by anorth** [comment]
I think an individual node's instance that has such an error can just be discarded and restarted, yet. It may have missed too much of the traffic to ever reach a local decision, but in that case an eventual finality certificate can move it along.

If all nodes suffer the same at the same time, obviously we have a bug that requires some intervention.

**Comment by anorth** [comment]
Thanks @Stebalien. To summarise what I think our agreement is:
- We should replace _most_ panics with errors, where the error is recoverable and the instance is ok to continue (already mostly done)
- Some cases of internal invariant violations can abort, and panic is a reasonable way to do this
- All panics must be trapped at the library entry points so they cannot crash the node

It might be reasonable for the multi-round protocol instance to do the catching of errors from individual instances, and discard their state and try again. So a little deeper than the client boundary.

**Comment by Stebalien** [comment]
> I think an individual node's instance that has such an error can just be discarded and restarted, yes. It may have missed too much of the traffic to ever reach a local decision, but in that case an eventual finality certificate can move it along.

But we _do_ need to remember to not participate, right?

> To summarise what I think our agreement is:

Yes. But...

> All panics must be trapped at the library entry points so they cannot crash the node

I'm slightly concerned that this could be tricky without adding defer/recover statements to every method. But we'll have to see, I guess.

**Comment by anorth** [comment]
@ranchalp I think the remaining work to be done here is catching panics at the Participant entry points
