### ISSUE TITLE
Change quality phase chain ordering to use epoch height instead of chain length

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#117]
The quorum state `ListStrongQuorumValues` prefers chains that are longer (have more non-empty tipsets), but should be comparing chains by EC epoch ("height") instead. The assertion that multiple chains can't have the same length isn't valid (but would be for same epoch).

**Comment by anorth** [comment]
I have forgotten why I said 

> the assertion that multiple chains can't have the same length isn't valid (but would be for same epoch).

This matters if we want to remove epoch from the tipset structure (#135). @ranchalp can you recall?

**Comment by ranchalp** [comment]
> I have forgotten why I said
> 
>>     the assertion that multiple chains can't have the same length isn't valid (but would be for same epoch).
> 
> This matters if we want to remove epoch from the tipset structure (https://github.com/filecoin-project/go-f3/issues/135). @ranchalp can you recall?

You said that because of null tipsets causing different lengths. It is not the case looking at the head epoch number.

**Comment by anorth** [comment]
Ok, so for example the chains
- [Base, nil, A]
- [Base, nil, nil, B]

...have the same length (because the nils are omitted) but different epoch heights.

It should be impossible to observe a strong quorum for both of these in the quality phase because neither is a prefix of the other. I think this issue was trying to establish an ordering between these two chains, but we don't need to.

If one chain is a prefix of another, then by construction they must have different lengths.

So... I think we're ok to keep ordering chains by length (# of non-empty tips), and panic if we observe strong quorum for two the same length. @ranchalp if you agree I think we can close this issue as ill-founded.

**Comment by ranchalp** [comment]
If nil tipsets are omitted always or must always be present then I agree. Closing.
