### ISSUE TITLE
Maximum ECChain Length

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#121]
If the network goes down for a while, the chain we all need to agree on could get pretty long. If that happens, we could (in theory) start sending messages that approach or exceed the maximum pubsub message size of 1MiB.

We should set some reasonable upper limit on the length of the ECChain. This will increase the time it takes to catch up to the main chain, but the limit can easily be hundreds. We should just have _some_ limit.

**Comment by jsoares** [comment]
Outcome from sync discussion: Let's take a pagination approach and limit to 100 epochs per instance. The relatively low number slows down catch-up after long halts, but it will be fast enough and minimises issues with unexpectedly larger than average messages and on-chain verification.

**Comment by anorth** [comment]
Note that this means [bootstrapping](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0086.md#bootstrapping) F3 when first activated will take 9 instances to catch up. But this seems fine.

**Comment by Kubuxu** [comment]
Was this codified?
