### ISSUE TITLE
Validate chains received

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#128]
There are some basic validation rules for ECChain values that we should enforce at all entry points (from messages and from the host).
- Epochs must be in order, monotonic (but may have gaps)
- Tipsets must not be zero value (this is also implied by epochs in order, if epoch >0)

Check other fields for validation rules too.

**Comment by masih** [comment]
Apologies in advance for pedantic questions:
* By monotonic, we strictly mean monotonically increasing with optional gaps where repeated epochs are also not allowed. Correct?
* Should `TipSetID`s also be included in validation?

**Comment by masih** [comment]
I have implemented validation based on the preexisting check that asserts there are no repeated epochs. Please let me know if that is unintended.
