### ISSUE TITLE
Resolve ECCompatible ("acceptable") chains as set of chains or single chain

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#132]
The FIP talks about EC Compatible chains as a collection of chains sharing some common prefix. The code constraints this to be a single chain that only ever extends from its head.

The single chain model allows a node to propose a block in EC during a running GPBFT instance and then ensure it doesn't vote against finalisation of its own block. I don't think a set of chains provides incentive-compatibility unless values can be removed from the set (or the set contents generally be arbitrarily updated by the node).

**Comment by ranchalp** [comment]
The FIP had a bug, ECCompatibleChains should be as the code specifies, which is one of the changes I propose to fix the bugs Guy found.

**Comment by anorth** [comment]
A proposed change to the protocol specification will remove the ECUpdate method, making this question mostly redundant. There will still be a "candidates" set of chains.

**Comment by anorth** [comment]
Closed with #181 (see #170)
