### ISSUE TITLE
Implement finality certificates

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#14]
Implement the creation of finality certificates from a strong quorum of signed DECIDE messages. See [design doc](https://docs.google.com/document/d/10i9tFremOSrZou9oO5A5wvu1uOy1lvFKbv8IsvoglR0/edit).

- Compute BLS aggregate signature
- Compute power table deltas
- Compute compressed participant-set representation
- Implement certificate validation

```[tasklist]
### Dependencies
- [ ] #5
- [ ] #4
- [ ] https://github.com/filecoin-project/go-f3/issues/150
```

**Comment by Kubuxu** [comment]
Initially, we can skip the deltas for MVP of this. So the minimal target becomes a format that allows for the validation of the aggregated decide message.
Stub for the certs lives here: https://github.com/filecoin-project/go-f3/blob/650d48b9a1b42d759422c247d136d847620ea0c8/certs/certstore.go#L18

It should expand to contain BLS signature, signers representation, and power table representation.
