### ISSUE TITLE
Use the whole chain when keying for proposals 

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#147]
Currently, we only use the head, which leads to confusion between ABC and ABxC chains.
https://filecoinproject.slack.com/archives/C06NTU2DPN1/p1712054917063199

**Comment by anorth** [comment]
Note this applies to both the quorumState used for most phases, and the convergeState. 

However, I am not sure how much of a problem this actually is. Finality decisions are ultimately about tipsets, and the data about the rest of the chain is in most cases redundant.
