### ISSUE TITLE
Align tipset identifier with the FIP

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#148]
The FIP at present specifies tipset identifiers as `[]Cid` in message. The code instead uses an opaque string (byte array). CIDs are opqaue to the protocol so there's not a good reason to depend on a CID package or import any semantics. But since CID has a specific IPLD tag, there's a mismatch to be bridged somewhere.

**Comment by Kubuxu** [comment]
Closing given https://github.com/filecoin-project/go-f3/issues/166
