### ISSUE TITLE
Use delayed power table to validate or drop messages from future instances

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#151]
We have agreed that voting weights for an instance should come from the power table resulting from not the immediately previous instance, but some distance (10 instances / 5 minutes? longer) further back. This allows us to do proper message validation and avoid retransmitting bad messages.

Since the power table is given from the node, it might be that theres little or no code change required in GPBFT, but (1) confirm this, and (2) ensure that multi-instance tests do this properly (#295), and (3) let's use #125 to help us gain confidence in the lookback distance.

```[tasklist]
### Tasks
- [x] #256
- [ ] #264
- [ ] #286
- [ ] #294
```

**Comment by anorth** [comment]
The point of this is to be able to validate message from near-future instances (from a node's point of view). So there will be work here to implement that validation and queue of _validated_ messages. This may involve changes to the host API so the participant can reliably keep track of N power tables and have the right one on hand for any message.

**Comment by anorth** [comment]
I'm closing #130 and expanding the scope here a little with a task list including maintaining the delayed power tables and  using them to validate messages.

**Comment by Stebalien** [comment]
IMO, we should use `int64` for instances _regardless_ (I've seen too many issues with MaxUint64 overflowing int64).

That aside, I don't think having the lookback inside go-f3 will actually be all that difficult:

1. We can still initialize instances with the desired power table (no lookback).
2. A `GetPowerTableFromInstance` method can simply assert that the passed instance has the correct lookback for the instance being simulated, then return the power table.

**Comment by Kubuxu** [comment]
We are storing finality certificates, which should contain the power tables that are being finalized.

**Comment by Stebalien** [comment]
Well, the finality certificates only store power table diffs. But looking up the power table associated with an instance isn't difficult (`instance - lookback_distance` -> head ts -> power table).

**Comment by Stebalien** [comment]
See https://github.com/filecoin-project/go-f3/pull/273/files#r1610685278 for an example of the power tables I'll need if we implement #257.

**Comment by anorth** [comment]
Testing effectiveness of this broken out to #295
