### ISSUE TITLE
Drop equivocations

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#153]
Prior versions of the protocol spec required a node to retain all equivocating messages (same instance, round, step and peer but different value). The code reflects this. The explicit justification removes that need, so the code should instead ignore equivocations. Change it to ignore all but the first message from a peer for each round and step (this will also help one angle of #12).

With luck, this can be done just by changing the quorum state data structures to be only able to represent one value per participant, and checking if such value has been received before updating.

**Comment by Kubuxu** [comment]
Is this complete with #145 or do we have to do more?

**Comment by ranchalp** [comment]
I have not gone through it yet, though it may be complete after #145 . Will do that,  but stuck with finishing touches on design docs.
