### ISSUE TITLE
Implement signed evidence-based message justification

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#16]
Implement the specified BLS-aggregate evidence-based version of the protocol. Messages should be justified just once and either processed or dropped. ~Expect constant memory complexity.~

We might hold this code in a branch while we continue to evaluate which justification method to use.

Requires #4 for signatures.

**Comment by anorth** [comment]
After investigating the cost of signing we realised that the evidence for a particular value at some round/step only needs to be evaluated once. So there will be some state to record which values have already been justified. Checking the evidence signatures for that value can then be skipped.

**Comment by ranchalp** [comment]
Resolved finally by #47
