### ISSUE TITLE
Observablility and metrics

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#160]
We should have metrics around round progression and the percentage of power voted (it might be tricky because we move on once a quorum is reached).
OpenCensus is the standard for it in the ecosystem.

- [x] signature validatiton time 
- [x] CPU & memory usage 
- [x] datastore size

**Comment by jennijuju** [comment]
add monitoring for metadata size growth

**Comment by masih** [comment]
@jennijuju Could you point me exactly to what we want to measure as "metadata size growth"?

My initial take is: size growth of every datastore namespace used by F3. Does that sound right?

**Comment by Stebalien** [comment]
@masih honestly, we can just monitor the "metadata" datastore itself. IIRC, that datastore is usually pretty much empty so it should be mostly F3 stuff.

**Comment by masih** [comment]
The only remaining item here is metadata size, for which I am not sure if Lotus metrics are exposed. I have posted something on fil-lotus-dev and pending response. 

For the rest the dashboard is updated to include them in addition to in-depth validation breakdown time, divergence, cert exchange, cert polling, gossipsub metrics.
