### ISSUE TITLE
Message re-broadcast, fast-forward and queues

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#169]
Tracking issue for the guaranteed broadcast issue.
@ranchalp can you post the latest update on it?
#139 #165 #136 #130

**Comment by ranchalp** [comment]
Design audited by Guy already and validated by Marko as well is [here](https://docs.google.com/document/d/1RNLyuvyg5v8Va-HonOk-FeluFFjyZEjJitMze7F67-Q/edit#heading=h.ae5wezjfdkpb).

**Comment by anorth** [comment]
Closing this in favour of:
- #151 
- #241 
- #242 
- #243
