### ISSUE TITLE
Head input chain offset

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/go-f3#175]
When a participant starts an f3 instance, it needs to determine whether it wants its proposal to contain from baseChain up to the head input chain it locally keeps in EC, or some prefix of it (i.e. offset it by some epochs). Although this may delay latency on the head tipset, it helps reduce latency and reach agreement faster on the EC instance. This is closely related with #173.

**Comment by ranchalp** [comment]
In pair with decision on #173 to wait for 2 epochs from the timestamp on the latest finalized epoch, the participant sets as proposal for the new f3 instance the following: 

- Let $baseChain$ represent the finalized chain up until the latest finalized f3 instance.
- Let $ECChain$ represent the current heaviest EC chain according to the participant (that extends $baseChain$ by design)
- Let $e'$ be the epoch at which the participant is starting the new f3 instance (following decision on #173 , $e' >= baseChain.head().epoch + 2$). 

Then: 
- If ECChain.head().epoch < e', participant sets its proposal to ECChain
- If ECChain.head().epoch = e', participant sets its proposal to ECChain[-1] (remove the head tipset, from the current epoch e')
- ECChain.head().epoch cannot be > e' by design (e' is the current epoch)

**Comment by anorth** [comment]
I think this is done: it is specified in the FIP so the decision is make. @Kubuxu do you need this issue open to track some implentation task?

**Comment by Kubuxu** [comment]
We don't have the head offset currently. Looking at the FIP pseudocode, it appears "delete the head always", as I'm assuming `CurrentEpoch()` is the epoch of the chain head and collecting the chain for `HeaviestUnfinalizedChain` will return that head.

**Comment by anorth** [comment]
It's difficult to be precise with language here. I had interpreted the FIP's use of `CurrentEpoch()` to mean the one for which new blocks are currently being transmitted but a tipset could not yet be confirmed by a subsequent block pointing to it. This is why it is always deleted. 

What exactly do you mean by the epoch of the chain head? Is it the epoch of the blocks currently being proposed? Or the epoch of the tipset to which the most recent possible block points?

**Comment by Kubuxu** [comment]
What you wrote here makes sense.
