### ISSUE TITLE
When to pull certificates 

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/go-f3#176]
A participant may be stuck trying to decide on an f3 instance. While the message rebroadcast mechanism #169 resolves this when no correct participant has terminated yet the instance (push of messages in current instance), if other correct participants have already terminated the instance, the stragglers need to ask for the finality certificate (pull). 

A decision needs to be made on when a stuck participant decides to ask around for certificates.

**Comment by ranchalp** [comment]
A suggestion is to set a periodic timeout to ask for certificates for the current instance.

Perhaps once per 30 seconds (once per epoch), if the participant has not terminated the current instance. This gives time to at least 2-3 rounds of the current instance before even asking (a request for a certificate is not a heavy message to send anyways). 

To be discussed though.

**Comment by Stebalien** [comment]
Given #151, we can probably be even looser with the timeout as we can validate up to N instances ahead.

**Comment by Stebalien** [comment]
If we haven't seen/agreed on an instance within some period of time, pull finality certificates with some exponential backoff.
