### ISSUE TITLE
Hash Function Decision

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#182]
We're settling on using merkle-trees for in several places (e.g., see #150 and #166) but we haven't settled on the hash function. This matters because, unfortunately, the EVM.

So, I'm going to suggest keccak256 to be EVM friendly, even though we don't use it _anywhere_ else. Otherwise validating merkle-trees could get a bit expensive.

That is, unless someone has a suggestion for a different snark-friendly hash function? But I'm not aware of an _efficient_ snark-friendly hash function.

**Comment by Kubuxu** [comment]
blake2b might be a better option for snarks, I would have to look into keccak256 padding rules to check if it has the same issue as SHA2/3 where hashing 64bytes requires two invocations of compression function due to padding rules.

**Comment by Stebalien** [comment]
If we were hashing a single large object, sha256 would be fine. But... the EVM charges 700 gas per call to the SHA2 precompile.

On the other hand, there's a KECCAK256 opcode that costs 30 gas plus 6 gas per word. So, validating a Keccak merkle-tree is _much_ cheaper.

**Comment by Stebalien** [comment]
Note: it looks like CometBLS uses [MiMC](https://union.build/docs/architecture/cometbls/#mimc-hashing) for zk compatibility. IMO, this won't matter _until_ we create a snark-friendly power table as we're planning on doing all of our hashing outside of snarks anyways.

**Comment by Stebalien** [comment]
We're using keccak256 for the merkle-trees.
