### ISSUE TITLE
Passively Test F3 on Mainnet nv24

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#213]
The following task list outlines the milestones required to complete the passive F3 testing on mainnet. 

See [F3 Mainnet Passive Test Plan](https://docs.google.com/document/d/14hMFN95_AsByBh7iMc4r_czUgg8tfjHQ1gTsmmHZ8jI/edit?usp=sharing) for more details.

- [x] https://github.com/filecoin-project/go-f3/issues/229
- [x] https://github.com/filecoin-project/go-f3/issues/226
- [x] https://github.com/filecoin-project/go-f3/issues/227
- [x] https://github.com/filecoin-project/go-f3/issues/228
- [x] **Calibnet Deployment:** Deploy the F3 protocol on Calibnet to mimic the conditions and processes of a mainnet rollout.
- [x] **Post-Calibnet Deployment Metrics Analysis:** Analyze the collected metrics for performance and correctness indicators. Confirm that all systems function as expected based on the metrics.
- [x] **Potential Pre-mainnet F3 Implementation Adjustments:** Based on insights from the Calibnet deployment, make any necessary adjustments. Freeze the F3 Alpha implementation in preparation for mainnet deployment.
- [ ] **Mainnet Deployment:** Roll out the optimized F3 implementation across the mainnet. Follow a phased approach to monitor performance and impact during the rollout.
- [ ] **Post-Mainnet Deployment Metrics Analysis:** Continuously monitor the F3 metrics post-mainnet deployment. Assess performance, correctness, and uptake to determine if further adjustments are needed.

**Comment by masih** [comment]
This was intented to be the top level umbrella issue. But now it's in Milestone 1. 

If that's where we want it to be then we should remove milestone 0 tasks from it.
CC @Kubuxu @jennijuju

**Comment by rjan90** [comment]
Goal is to get up to 1000, but unclear if it is possible to get that number with the rollout of v0.2.0

**Comment by Stebalien** [comment]
We're going to punt the first round of testing till tomorrow to give the pubsub mesh some time to form (needed to reboot the bootstrappers to join the new network).

**Comment by rjan90** [comment]
@masih Can we close this ticket, and instead open smaller testing tickets for individual passive testing efforts?

**Comment by masih** [comment]
> Can we close this ticket, and instead open smaller testing tickets for individual passive testing efforts?

My recommendation is to indeed open smaller tickets for explicit test efforts, _and_ reference them under this one. Because: 1) this is the ticket that has been referenced in previous community posts. 2) it gives the community a single point of reference into what actually gets tested in passive testing along with the ability to drill down further should they want to learn.

**Comment by rjan90** [comment]
- Phased approach - run it in a few steps
   - Thursday/Friday (2024-11-21 & 22) get back into tooling, deploy with a few percentage of the network.
   - Monday (2024-11-25) start with 10 and then ramp up to 30, 50 and 100 percent.

**Comment by rjan90** [comment]
### This is what happened last week

- Last Friday we got back into tooling, and deployed passive testing with around 5 MinerIDs participating in the passive testing. It ran successfully over the weekend without any hiccups.

### This is the plan for this week

- Today (2024-11-25) we are planning to bump the participation to 100 MinerIDs, then we will continue to bump it towards 200 MinerIDs joining passive testing, 600, 1000 and everyone (approximately 2000 MinerIDs)

**Comment by BigLep** [comment]
I'm scoping this issue to the nv24 passive testing.  There is a followup issue for nv25 passive testing in https://github.com/filecoin-project/go-f3/issues/802 .  As a result, I think we can close this issue.
