### ISSUE TITLE
Fuzz RNG seed in simulation tests

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#218]
The number of rounds required for consensus in simulations is directly influenced by the latency modeling, which simulates 
message propagation delay across the network.

Currently, many tests rely on repetitive executions with varying RNG seeds to simulate random effects. While this approach 
allows for parallel testing, it still relies on deterministic seed choices.

To improve testing efficiency and separate concerns between development unit testing and fuzz testing, we should integrate 
fuzz testing capabilities into our tests. This change will enable:

1. Faster testing cycles during development, as developers won't need to wait for all repetitions to complete and fuzzing can be delegated to CI workflow marked as required to pass per PR.
2. Configurable fuzz testing with adjustable lengths of time.
3. Adherence to Golang best practices.

This improvement should also help catch edge cases like #196 more effectively, reducing the likelihood of similar issues in 
the future.

**Comment by anorth** [comment]
> developers won't need to wait for all repetitions to complete

I don't understand this. Why not? Just using a different random seed doesn't make tests any better at covering the search space. Failures often happen deep in the iterations at present. If we do fewer iterations, we just won't find the bugs.

**Comment by masih** [comment]
Description updated to clarify that the fuzzing can be delegated to a CI job run elsewhere.
