### ISSUE TITLE
Remove weight from tipset (was: confirm whether tipset weight can use uint64)

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#22]
The tipset information includes weight, for comparing heaviest. Will weight values always fit in a uint64?

**Comment by matejpavlovic** [comment]
In fact, this might not be the same as in Spacenet... In Spacenet, the voting weight of a participant had to be a `big.Int`, since the amount of staked FIL (for which Lotus uses a `big.Int`) was used as the weight. I do not actually know what Lotus uses to express the tipset weight. @Kubuxu ? :-)

**Comment by ranchalp** [comment]
It uses [Big.Int](https://github.com/filecoin-project/lotus/blob/ff0fa3471f1489bb32b06ccae53041539a4725e3/chain/types/blockheader.go#L52). We should change this then.

**Comment by ranchalp** [comment]
However, assuming the same growth in the cumulative weight of a tipset that was experienced from right now to last year (i.e. from tipset at height #2557324 to tipset at height #3608526), it would take 726,578,793 years before we exceed uint64, so perhaps we do not want to use big.Int if we want compact finality certificates.

**Comment by anorth** [comment]
@Stebalien @ranchalp and I discussed and decided that, since the ties being broken here require the <=33% adversary assumption to be broken, it would be better to halt the protocol if there is any chance of nodes deciding different values.

So let's remove weight altogether, and halt when observing two strong quorums.

**Comment by anorth** [comment]
Closed by #71
