### ISSUE TITLE
GossipSub / Lotus Integration

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-f3#225]
Integrate the F3 protocol with GossipSub as the message transport and propagation mechanism. Connect the integrated system with the existing Lotus EC component to support an alternative consensus protocol.
```[tasklist]
### Tasks
- [ ] #13
- [ ] #14
- [ ] #15
- [x] Integrate with Lotus, plug in EC
- [ ] https://github.com/filecoin-project/go-f3/issues/364
```

**Comment by Kubuxu** [comment]
I'm going to close this as solved, leaving only the Lotus integration epic up.
