### ISSUE TITLE
Monitoring Infrastructure Setup

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/go-f3#227]
Establish a centralized monitoring infrastructure to collect metrics from nodes for real-time monitoring and analysis.

**Comment by Kubuxu** [comment]
We need to deploy grafana to collect metrics.
See: https://github.com/filecoin-project/go-f3/blob/main/metrics.go
https://github.com/filecoin-project/go-f3/blob/main/gpbft/metrics.go

**Comment by masih** [comment]
This issue is actually two things: 
* grafana dashboard setup + prometheus metric scraping to populate it; This is done.
* standalone observer node implementation which I think @Kubuxu is working on.

I am going to adjust this issue to only capture the former, and create a new issue for the latter.
