### ISSUE TITLE
Testing utilities for passive testing in network deployment

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#229]
- configuration format suitable to execute test scenarios
- configuration propagation
  - Manifest version in the gpbft messge
  - Manifest fetching
  - applying the manifest 
- re-bootstrapping
- power table editing

**Comment by masih** [comment]
I think we can move all of this as sub tasks under https://github.com/filecoin-project/go-f3/issues/227

**Comment by Kubuxu** [comment]
The intended difference between these two is timing. This needs to land before the Lotus release.

**Comment by masih** [comment]
@Kubuxu I think we can mark this as done?
