### ISSUE TITLE
HasWeakQuorumFor never called

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#233]
Nothing calls `HasQeakQuorumFor`, or ever reads `chainSupport.hasWeakQuorum`. Should we remove this? Or are we missing a part of the protocol.

**Comment by anorth** [comment]
Defer this for a bit, it's currently unclear whether we'll end up calling it as part of skipping rounds. It was also in the FIP for another reason until very recently.

**Comment by jennijuju** [comment]
@anorth  - can you please take a look at this and see what needs to be done here now that we have more clarity on the protocol?

**Comment by masih** [comment]
Skipping rounds is complete, and uses the notion of weak quorum in quorum state only. I'll remove the unused flag from chain supprot.
