### ISSUE TITLE
Short-cut timeout in PREAPRE, COMMIT when justified by received messages

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#242]
```[tasklist]
### Tasks
- [x] Skip the timeout in PREPARE after it's impossible to reach a strong quorum in agreement with the local proposal.
- [ ] Skip the timeout in COMMIT after receiving a strong quorum of anything, including bottom.
```
See https://github.com/filecoin-project/FIPs/pull/998

**Comment by masih** [comment]
Capturing discussion from Slack on the second task in this issue, i.e. shortening timeout for commit.

> The protocol assumes that when it sends a message, it is going to receive that message before it receives anything else, so it can rely on the state updates (it used to do so internally, synchronously). However, the simulation is delivering an alarm before delivering the converge message that the participant sent to itself.

But with the introduction of [async message reception](https://github.com/filecoin-project/go-f3/pull/259) this assumption no longer holds.

> We can probably fix this in simulation fairly easily, but it's a subtle but important requirement on the production host too. This came about because the participant can no longer sign its own messages (doesn't even know its ID).

> ...it will be a bit harder to fix outside of the simulation. There is no guarantee that anyone will sign the message we requested broadcast for, and even if there is someone that will sign it, it would require us to block everything until the do.
This is also a requirement for the passive node (there is nobody to sign the messages, and we are just processing ones coming from the network.
