### ISSUE TITLE
Provide API for host to force progress from finality certificates

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#245]
If a node gets really stuck, we expect the host to fetch finality certificates and use those to force a node up to a new instances without passing through the full protocol. We need some API capability for this; it might also overlap with initial bootstrapping.

Since validating a finality certificate depends on previous certificates, probably the host will do the validate then just tell the GBPFT participant where to skip to (and provide the necessary history of power tables for it to validate messages). But other orchestrations might be possible too.

FYI @Kubuxu

**Comment by jennijuju** [comment]
cover #245?
