### ISSUE TITLE
Investigate fuzzing process hung or terminated unexpectedly

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#251]
Specific fuzz tests seem to sporadically fail with error: `fuzzing process hung or terminated unexpectedly: exit status 2`. This could be a bug of sorts in the fuzzer itself as outlined in https://github.com/golang/go/issues/56238. Or possibly a panic during simulation?

See example CI fuzz failure [here](https://github.com/filecoin-project/go-f3/actions/runs/9133502075/job/25117189120).

**Comment by masih** [comment]
More context:
* this failure is intermittent. For example, rerunning [this](https://github.com/filecoin-project/go-f3/actions/runs/9157403508?pr=252) build passed.
* it seems to be sensitive to the fzzer worker count. I can reproduce this locally with `-parallel=4`, i.e. what the CI fuzzer picks.

**Comment by masih** [comment]
More context:
* seems to always fail for `FuzzHonestMultiInstance_AsyncAgreement`

**Comment by Kubuxu** [comment]
Each fuzz run cannot take longer than 10s: https://github.com/golang/go/blob/019353d5323fcbffde939f4e85a68bd0093c6e14/src/internal/fuzz/worker.go#L492-L494

**Comment by masih** [comment]
Yep that's pretty much the conclusion in the golang issue linked in the description, in that timeout is not configurable in fuzz tests.

**Comment by Kubuxu** [comment]
Might be still a bit too slow, at least for my machine:
```
--- FAIL: FuzzHonest_AsyncMajorityCommonPrefix (20.17s)
    fuzzing process hung or terminated unexpectedly: exit status 2
    Failing input written to testdata/fuzz/FuzzHonest_AsyncMajorityCommonPrefix/6bac56228674bce6
    To re-run:
    go test -run=FuzzHonest_AsyncMajorityCommonPrefix/6bac56228674bce6
```

**Comment by Kubuxu** [comment]
Or not, it is a different test

**Comment by masih** [comment]
I think I know why `FuzzHonest_AsyncMajorityCommonPrefix` fails. I'll do a re-scan of fuzz tests.

**Comment by masih** [comment]
OK thanks. Since this issue is closed CI has been passing consistently? unless I have missed a failure. Having said that, that could be fluke.

I'll take a closer look at the fuzz tests.
