### ISSUE TITLE
Commit to the next power table in the message payload

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#257]
#151 makes it difficult to validate finality certificates by introducing a power lookback. Right now, given the previous power table and a finality certificate, I can generate the "next" power table and validate it by checking the `PowerTable` CID in the last finalized epoch. After this change, I won't be able to do that.

One solution is to commit to the power table used to validate the _next_ instance in the message `Payload` itself (and possibly remove it from the tipset list). This would be somewhat annoying _at the moment_ because the "next" power table can change over the course of an instance as we try to find the longest common prefix. However, given a lookback of at least one instance, this value will be consistent for all participants in the instance.

**Comment by Stebalien** [comment]
Discussed in standup:

1. Regular light clients only need the power table used to validate the _next_ finality certificate.
2. Regular GPBFT participants can always get their power tables from lotus if/when participating in voting (can't participate in an instance (except decide) unless they've synced that chain).
1. However, we may want GPBFT _followers_ that follow the GPBFT chain without syncing the main chain. For these clients, having "future" power tables (the power tables as they're finalized) without having to talk to lotus could be useful.

So, I'm proposing:

```go
type Payload struct {
	// ...
	Value Value
}

type Value struct {
	// Power table from the base tipset.
	BasePowerTable Cid
	// Power table used to validate the next instance.
	NextPowerTable Cid
	// Arbitrary commitment tree, used primarily for snark-friendly power tables. Unused for
	// now.
	Commitments [32]byte
	// The chain being finalized.
	Chain ECChain
}
```

The signing format will change to: 

```
DSTPrefix || Step || Round || Instance || \
    Digest(BasePowerTable) || Digest(NextPowerTable) || \
    Commitments || \
    MerkleRoot(Chain)
```

I'm also proposing that we _remove_ the power table from each tipset:

```go
type TipSet struct {
	// The EC epoch (strictly increasing).
	Epoch int64
	// The tipset's key (canonically ordered concatenated block-header CIDs).
	Key TipSetKey
	// Keccak256 root hash of the commitments merkle tree.
	Commitments [32]byte
}
```

NOTE: we're including the _base_ power table in the `Value`, not the _head_ power table. Unless we involve lotus to get the head power table from the last instance, this reduces the _effective_ lookback by 1. 

Alternatively, we could use the head power table, but then we'd need to add the power tables back into the tipset objects. By excluding it from the tipset objects, we can avoid computing the CID for _every_ power table and instead just need to compute it for the last tipset finalized in each instance.

**Comment by Stebalien** [comment]
In terms of finality certificates, we'll need to support _two_ formats:

1. One that tracks the _latest_ finalized power table.
2. One that tracks the power table used to validate the next instance (the next finality certificate).

Only GPBFT "followers" will use the first protocol, light clients will use the second so they don't have to understand and/or care about the power table delay (which also gives us more leeway to change it in the future).

**Comment by Stebalien** [comment]
EDIT: I split the value into data/chain for simplicity. Otherwise the refactor is going to be annoying.

1. `Data` can be trivially constructed when we start an instance and validated when we receive a message by checking for equality.
2. We can then ignore `Data` in the rest of the protocol (except when sending messages, because we need it to be signed).

In theory, we could drop it from our messages entirely and supply it when validating message signatures. But that doesn't seem worth it.

**Comment by Stebalien** [comment]
A downside of the "support both" solution is that validating finality certificate chains still requires lookback. One option is to _always_ include the delta for validating the next finality certificate (lookback power table), and optionally include a delta for the base power table (latest power table). It's a slight waste of bandwidth, but so minimal it shouldn't be a huge issue in practice.

But including the lookback table is going to be kind of annoying regardless of what we do...

**Comment by Kubuxu** [comment]
Rename NextPowerTable to NextValidationPowerTable

**Comment by Stebalien** [comment]
MVP: Put `NextPowerTable` (or `NextValidationPowerTable`) in the root.
Maybe: Remove the power table from the tipsets and add a base power table to the root.

TODO: Benchmark generating power tables per tipset. @Kubuxu pointed out that only using the base power table could help with catch-up.

**Comment by Stebalien** [comment]
Benchmark results: It's taking about 1.5s to walk the power table hot, or 4.3 when cold.

_However_, that's without any diffing or parallelism, both of which are options for us (we already have the diffing code courtesy lily). So I doubt this is going to be a huge performance issue.

**Comment by anorth** [comment]
(Catching up) 

> By excluding it from the tipset objects, we can avoid computing the CID for every power table and instead just need to compute it for the last tipset finalized in each instance.

I think this is what you've just benchmarked, but I would question whether computing the power table CID for each EC epoch is really much of a burden.

Your MVP proposal sounds good.

I think it's probably fine for light clients to deal with the lookback. So the deltas are for the power table just finalised, and validation requires holding on to 10 most recent computed versions. Are your changes attempting to avoid that?

**Comment by Stebalien** [comment]
> I think this is what you've just benchmarked, but I would question whether computing the power table CID for each EC epoch is really much of a burden.

Yes, that's what I benchmarked. And it doesn't look like a burden _except_, possibly, if we're running in 'catch up' mode.

> I think it's probably fine for light clients to deal with the lookback. So the deltas are for the power table just finalised, and validation requires holding on to 10 most recent computed versions. Are your changes attempting to avoid that?

My plan was to support deltas for both and let the client decide which deltas they want to request. But I'm still working out the details.

You're right that the client _could_ handle lookback, but I'd rather not have clients care about it. It simplifies the client logic and means we can change the lookback in the protocol itself without touching the clients.

**Comment by Stebalien** [comment]
NOTE: I've tried diffing and the performance was actually worse. Not sure why yet (I'm testing on a live node so it could be other factors).

**Comment by Stebalien** [comment]
Ok:

1. I'm going with the MVP (only commit to the _next_ power table in the root, commit to all other power tables in the tipsets).
2. @Kubuxu I'm just calling it `PowerTable` as it should be pretty unambiguous now. We're explicitly agreeing on the power table used to validate the next instance (even though we should all _already_ agree).
