### ISSUE TITLE
Require that justifications have the minimum required power?

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#261]
Right now, a justification can include as much power as it wants as long as it includes at least 66%. Given that we sort the power table from most power to least power, it's pretty trivial to determine if a justification has more power than necessary.

- Do we want to reject justifications with _too_ much power?
- Do we want to reject _finality certificates_ with too much power?

Really, I only care about the second question. There's no way to force participants to "optimally" select signatures for justifications, but we _can_ prevent them from adding in completely superfluous signatures.

My gut is that this probably doesn't matter given that we can't ensure the uniqueness of finality certificates _anyways_, but I figured I'd bring it up.

**Comment by Stebalien** [comment]
This doesn't seem worth it, IMO.

**Comment by anorth** [comment]
The same question came up for committee signatures on anything (e.g. justification for a COMMIT). I concur I don't think it's worth limiting.
