### ISSUE TITLE
Interference in parallel tests with TestHonestMultiInstance_Agreement

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#262]
When enabling more test parallelism, I ran into a failing test for multi-instance agreement only when run in parallel with other tests. When `TestHonestMultiInstance_Agreement` is run in isolation, it always passes. When run in parallel with all other tests, the third iteration always fails with too many rounds. Parallelism was obtained with `t.Parallel()` in both `TestHonestMultiInstance_Agreement` and inside the nested `t.Run()`.

My IDE is running `go test -json -parallel=8 -count=1 ./... -run ./...`, and I replicate the failure with this at CLI. However, removing the `-json` flag causes the tests to pass at CLI 😕.

```
=== RUN   TestHonestMultiInstance_Agreement/async_3
=== PAUSE TestHonestMultiInstance_Agreement/async_3
=== CONT  TestHonestMultiInstance_Agreement/async_3
    multi_instance_test.go:113: 
        	Error Trace:	/Users/me/pl/src/filecoin-project/go-f3/test/multi_instance_test.go:113
        	            				/Users/me/pl/src/filecoin-project/go-f3/test/multi_instance_test.go:46
        	Error:      	Received unexpected error:
        	            	reached maximum number of 10 rounds
        	Test:       	TestHonestMultiInstance_Agreement/async_3
        	Messages:   	P0{593}, round 10, phase COMMIT
        	            	P1{593}, round 11, phase CONVERGE
        	            	P2{593}, round 10, phase COMMIT
--- FAIL: TestHonestMultiInstance_Agreement/async_3 (0.25s)
```

**Comment by anorth** [comment]
It looks like on CI the interference is triggered even more easily. [This run](https://github.com/filecoin-project/go-f3/actions/runs/9182153607/job/25250463506?pr=263) had no `t.Parallel()` at the top of `TestHonestMultiInstance_Agreement`, only within each `t.Run()`. I guess I'll have to disable the inner one too.

**Comment by masih** [comment]
Thank you for capturing this issue. I suspect it's related to sporadic Fuzz failures too ([example](https://github.com/filecoin-project/go-f3/actions/runs/9182236551/job/25273069440?pr=263)).

**Comment by masih** [comment]
Update: 

I am able to reproduce this failure locally by running:
```
 go test -run TestHonestMultiInstance_Agreement -count=100 -parallel=20 ./test -v -failfast
```

The value of `-parallel` doesn't matter, nor does where `t.Parallel()` is placed (atop `TestHonestMultiInstance_Agreement`, or at each run, or both). e.g. I can reproduce this with `-parallel=1`.
