### ISSUE TITLE
FIP: Specify the BLS algorithm

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#285]
> The protocol assumes aggregatable signatures (e.g., BLS, Schnorr), resilient to [rogue public key attacks](https://crypto.stanford.edu/~dabo/pubs/papers/BLSmultisig.html) (see [Boneh, Drijvers, and Neven](https://eprint.iacr.org/2018/483.pdf) construction).

We need to specify the exact BLS algorithm we use.

**Comment by Stebalien** [comment]
@Kubuxu could you add a line to the FIP specifying this?

**Comment by Stebalien** [comment]
It's not.

**Comment by Stebalien** [comment]
Specifically, document #592.

**Comment by Stebalien** [comment]
https://github.com/filecoin-project/FIPs/pull/1064

**Comment by rjan90** [comment]
Closing as https://github.com/filecoin-project/FIPs/pull/1064 has been merged
