### ISSUE TITLE
Receiving alarms must take precedence over receiving broadcasted messages

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#316]
The GPBFT algorithm assumes that when an alarm is triggered it will get delivered at the designated time _before_ a broadcasted message that so happens to arrive at the same time.

This assumption does not hold in the current simulations, where all messages including alarms use the same queue for delivery prioritised by `deliverAt` timestamp regardless of whether they are an alarm or broadcasted messages.

* Respect the priority of alarms in simulation.
* Document this requirement at `gpbft.Clock`.

**Comment by Kubuxu** [comment]
https://github.com/filecoin-project/go-f3/issues/319
Given the above and async signing, this is not a property I can easily guarantee in a real system.

**Comment by anorth** [comment]
This spawned from #242, but that says the protocol...

> assumes that when it sends a message, it is going to receive that message before it receives anything else

I.e. **messages first**, in the particular case of a send to self. So on the surface this strikes me as not the right fix.

It's also not documented in the code **why** the alarm-before-message assumption exists, and e.g. what would have to change for it to no longer be required (currently, it's just asserted with no justification). This should be documented somewhere in gpbft or the host API.

(The "why" for messages first is: so a send to self is received as if synchronously)

**Comment by anorth** [comment]
@Kubuxu noted in #318 that for message-over-alarm precedence

**Comment by anorth** [comment]
> > (The "why" for messages first is: so a send to self is received as if synchronously)
> 
> One can say the same about alarm. right?

I don't think there's any need for synchronous alarms. If code setting an alarm wants synchronous triggering, it should just call the trigger directly. Alarms are specifically to invoke asynchrony. The code (but not the FIP) uses "alarm at now" to invoke asynchrony with no delay just to unify the execution path into some bits of code, like starting a protocol instance.
