### ISSUE TITLE
Settle representation of voting power, truncation of native power

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/go-f3#33]
Confirm if voting power can use uint or needs big.Int. Similar to the concern raised in #22.

Update: expanded scope to include design question about truncation

**Comment by ranchalp** [comment]
It uses `big.Int`. See [this](https://github.com/filecoin-project/lotus/blob/8b5da86727d251de7703680d5c3db1c21987b762/chain/actors/builtin/power/power.go#L164), [this](https://github.com/filecoin-project/go-state-types/blob/f4366fdb96de135e00911166c1b461f0c2bdd52e/abi/sector.go#L65) and [this](https://github.com/filecoin-project/lotus/blob/a3417e7488356d97ada733ffa27a7df22b6d1d16/api/api_full.go#L1078).

**Comment by Stebalien** [comment]
It does, but it probably doesn't _need_ to if we're willing to lose some precision.

**Comment by ranchalp** [comment]
Is there a benefit to losing precision? I do not see it currently

**Comment by Stebalien** [comment]
Smaller power table updates. E.g., if I can truncate to the nearest 32GiB, I can save ~4 bytes per entry. I can save 5 bytes per entry if I can limit power increments to 1TiB.

This will also let us limit the number of power table updates (as long as an update wouldn't cross over a 1TiB boundary).

**Comment by anorth** [comment]
Truncating power is a good design question which has occurred to us, but not been investigated in depth. I'll retitle this issue to reflect that, and add to our meeting agenda.

**Comment by anorth** [comment]
I think changing the go-f3 representation to big int right now is the safest thing to do. Even if we truncate, we might still want a bigint to future-proof it.

**Comment by Stebalien** [comment]
So, goals are are:

1. Small power-table diffs: small power values, fewer power updates.
2. Avoid "rewrite everything" updates to power tables stored, e.g., in bridge smart contracts.

One interesting issue will be, e.g., if power _shrinks_ appreciably. We'd need some way to "add back" precision and probably want some way to avoid constantly changing how we truncate.

**Comment by Stebalien** [comment]
If we truncate the power by one byte (divide by 256) each time we reach some threshold, we can:

1. Remove precision in smart contracts by masking power values (avoids expensive state updates).
2. Add precision back by transmitting a single byte-array (least significant bytes for all powers). However, this update _will_ be expensive to process.

I'd like to avoid having any unstable points where it's possible to repeatedly trigger steps 1 & 2, but that's going to require some hysteresis. I guess that's fine?

**Comment by anorth** [comment]
See also #5 , which will probably resolve this too

**Comment by Stebalien** [comment]
For completeness, I looked into scaling power to the range 0x0-0xFFFF based on the total fraction of power. The idea was to avoid "cliffs" where we'd need to suddenly "add back" precision.

Unfortunately:

1. By scaling this way, we get some epochs with > 600 power changes (over the course of 1000 epochs). Not unexpected, but unfortunate.
2. If we don't scale _at all_, we get 0-4 power changes over that same 1000 epochs.

So I'm going to discount scaling as a possible solution to reducing the size of the deltas, but it may still have a place...

Additionally, given the low frequency of power changes, I'm inclined to discard truncation as well (for now). If necessary, we can smooth out power changes in the Filecoin protocol itself at some later point.

**Comment by Stebalien** [comment]
So, current thoughts on scaling/truncation:

1. Represent power _changes_, new keys, etc. in terms of raw (unscaled, untruncated) power changes. Do _NOT_ commit to these.
2. Commit to a full power table (unscaled/untruncated) _for now_.
3. Make consensus decisions after scaling all power to the range `0-0xFFFF`. Specifically, `truncate((0xFFFF * Power)/TotalPower)`. The cost of scaling power on the fly should be minimal and it'll make some future optimizations possible.

Specifically, I want to scale power for consensus decisions because it'll let us (eventually) commit to a scaled power table which:

1. Will be small (2 bytes per participant). This will make it a good fixed-ish size fallback in case we get large power swings.
2. May work better in zero knowledge proofs (fixed size)?
