### ISSUE TITLE
Supplemental data is not broadcasted

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#335]
The supplemental data is not broadcasted. Messages are not received if a participant is passed non-zero supplemental data from `GetProposalForIstance`. When broadcasting is fixed, verification of aggregates fails.

**Comment by Kubuxu** [comment]
See https://github.com/filecoin-project/go-f3/pull/336 for example of the issue

**Comment by Stebalien** [comment]
Should be:

```diff
diff --git a/gpbft/gpbft.go b/gpbft/gpbft.go
index c56f1ce..964fab6 100644
--- a/gpbft/gpbft.go
+++ b/gpbft/gpbft.go
@@ -899,10 +899,11 @@ func (i *instance) terminated() bool {
 
 func (i *instance) broadcast(round uint64, step Phase, value ECChain, createTicket bool, justification *Justification) {
 	p := Payload{
-		Instance: i.instanceID,
-		Round:    round,
-		Step:     step,
-		Value:    value,
+		Instance:         i.instanceID,
+		Round:            round,
+		Step:             step,
+		SupplementalData: *i.supplementalData,
+		Value:            value,
 	}
 	mb := NewMessageBuilder(&i.powerTable)
 	mb.SetPayload(p)
```

**Comment by masih** [comment]
Yep plus generating non-zero ones in sim. Working on it.

**Comment by Kubuxu** [comment]
@Stebalien that is what I did but it resulted in invalid aggregates

**Comment by masih** [comment]
> it resulted in invalid aggregates

Because GMessage doesn't contain supplimental data I think. I'll have a PR for you by EOD.
