### ISSUE TITLE
Filter SP representation in F3 power table by threshold etc

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#346]
FIP-0086 says
> Only SPs that hold more than the threshold of power to participate in EC can participate in F3.

The raw power table needs filtering by this threshold function (which happens at use-time in other places). Implicit, but I assume the total F3 power should be the sum of the eligible entries, not the EC total.

EC also has other use-time filters on eligibility, such as not being in consensus fault or fee debt. The FIP doesn't mention those things, so we need to decide whether those conditions should apply to F3 too, and document and/or implement that behaviour.

Some of the logic might be difficult to encapsulate in this repo without depending on Filecoin chain state, in which case we should at least document the expectations here, and open an issue somewhere else to track.

**Comment by Stebalien** [comment]
> EC also has other use-time filters on eligibility, such as not being in consensus fault or fee debt. The FIP doesn't mention those things, so we need to decide whether those conditions should apply to F3 too, and document and/or implement that behaviour.

IMO, yes.

> Some of the logic might be difficult to encapsulate in this repo without depending on Filecoin chain state, in which case we should at least document the expectations here, and open an issue somewhere else to track.

Something is going to have to understand the Filecoin representation of the power table anyways, so I expect that something will do the filtering before returning the F3 representation of the power table.

**Comment by anorth** [comment]
https://github.com/filecoin-project/FIPs/pull/1022 specifies the filters

**Comment by Kubuxu** [comment]
This is done one the lotus side.
