### ISSUE TITLE
FIP completion and alignment with code

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#347]
Ensure the FIP and implementation code are aligned in all necessary details, and that the FIP is complete enough to be a specification for another implementation (e.g. in Forest/Rust).

```[tasklist]
### Tasks
- [ ] Specify power threshold and applicability of other EC filters on power table participation (consensus fault, fee debt, etc). See #346
```

**Comment by Stebalien** [comment]
https://github.com/filecoin-project/go-f3/issues/244?

**Comment by anorth** [comment]
Closing for #244
