### ISSUE TITLE
Weird behaviour when racing in small network

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#372]
Given a gpbft network with one node with all the power and no sleep from Recieve Decision (due to the EC head being far in the past), I've observed that the node will race-produce instances for a while and then stop for a few seconds in the quality phase (until the asynchrony timeout).

This might be a non-issue, but it hints at some indeterminism.

**Comment by anorth** [comment]
The racing makes sense (until #371), but I'm not sure why it would stop.

**Comment by Kubuxu** [comment]
Yeah, the racing is not what made me create this issue, it is the pauses in the Quality phase that did.

**Comment by Stebalien** [comment]
I'm _guessing_ this is because the racing nodes are getting "strung out", with more and more falling behind over time. Eventually, you don't have enough in the quality phase to make progress (till they all catch up due to the exponential round backoff).

**Comment by anorth** [comment]
> I'm _guessing_ this is because the racing nodes are getting "strung out", with more and more falling behind over time.

The context is one node with all the power, though.

**Comment by Stebalien** [comment]
Oh... ok, yeah, that's weird.

**Comment by rjan90** [comment]
@Kubuxu Have a confirmation that this is only happening in small networks?

**Comment by masih** [comment]
I think we resolved that [a while back](https://github.com/filecoin-project/go-f3/pull/369)?
