### ISSUE TITLE
Pause F3 until a new configuration manifest is received 

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/go-f3#390]
We should include in the manifest a flag to say F3 to pause until the next manifest with a new configuration is received. While F3 is paused, the runner and the pubsub topic for F3 will be disabled, and the the node will only be listening to the reception of new manifests.

//cc @masih

**Comment by masih** [comment]
Thank you for capturing this

**Comment by jennijuju** [comment]
I think this ideally should be included in the  go-f3 release that goes with  the final calib release of lotus. @masih @adlrocha lmk if you agree
