### ISSUE TITLE
"Signers" can join half-way through a round/instance

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#393]
If a "miner" process calls `SubscribeForMessagesToSign` half-way through a round/instance, they'll start signing messages without signing the prior messages. Given that any message can be dropped, maybe this is fine? But I wanted to make sure because the _local_ gpbft instance won't have seen these messages which is... unusual.

**Comment by Kubuxu** [comment]
I think this is fine. They were absent previously (as if their messages were dropped) and are re-joining.

**Comment by Stebalien** [comment]
What if they switch from one lotus node to another?

**Comment by Kubuxu** [comment]
It gets more complex (possibility of equivocation), but I still think it is fine (in the context of lack of fault fees).

**Comment by masih** [comment]
Is this still an issue now that `SubscribeForMessagesToSign` is gone?

**Comment by Kubuxu** [comment]
Conceptually yes, but I don't think the conceptual issue is a problem.
