### ISSUE TITLE
Rebroadcast overloads the broadcast bus

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#443]
Rebroadcasting writes a bunch of messages to the broadcast bus all at once, which causes subscribers to be disconnected after they fall behind.

We probably shouldn't use this "bus" in this case but should instead directly write to a channel. Then, we can handle the "broadcast" part in the client.

**Comment by masih** [comment]
This is in the `f3` package and not in `gpbft right?

**Comment by Stebalien** [comment]
I started working on this and I don't think a blocking channel is the right approach either. I think we want something more flexible:

1. Participants should be able to join late and still sign messages.
2. GPBFT should be able to _cancel_ messages that are too old.
3. We should never drop messages to sign until they're tool old.

I'm thinking something like:

1. Participants call `Subscribe() *Subscription` to get a subscription, then `Subscription.Next()` each time they want to sign a new message.
2. In addition to "broadcast", GPBFT can "cancel broadcast" on all pending messages (e.g., when advancing the protocol).

Importantly, subscriptions will return all relevant messages to sign, not just messages broadcast after subscribing.

**Comment by Stebalien** [comment]
Ok, talked with @Kubuxu and channels are probably good enough for now.
