### ISSUE TITLE
Handle "reorg away from base"

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#447]
This isn't allowed by F3 but is possible in a test setup where EC doesn't care about F3. We need to get rid of the panic here:

https://github.com/filecoin-project/go-f3/blob/5aa1e0123235af94318439c2675048b060a26d59/host.go#L370

I'm not entirely sure what we _should_ do. IIRC, the plan is to run F3 with a several epoch lag to make this _unlikely_ but, if this happens, simply reorging away from the base will cause... problems.

**Comment by Kubuxu** [comment]
I think the best solution then is to vote base, which will trigger backoff. If EC re-orgs back onto base, we will continue; if not, we will trigger re-bootstrap.
