### ISSUE TITLE
Set up missing `UCI_GITHUB_TOKEN` secret

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#449]
https://github.com/filecoin-project/go-f3/actions/runs/9894658122

**Comment by masih** [comment]
Using default secret also doesn't seem to work: https://github.com/filecoin-project/go-f3/actions/runs/9939568414/workflow#L22

**Comment by Stebalien** [comment]
We've only given web3-bot write access. Does it need higher privileges?

**Comment by masih** [comment]
Not according to the documentation (and past experience). But then `UCI_GITHUB_TOKEN` doesn't seem be documented. @Stebalien could you check if that secret exists at org level and if so go-f3 has access to it please?

**Comment by Stebalien** [comment]
I only see a codecov token.
