### ISSUE TITLE
Manifest power update is insufficient for limiting participants

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#463]
Specifically, it lets us change power but doesn't let us straight-up set it. So:

1. If the power goes down, the delta will drop below zero and applying it will fail.
2. If the participant's power goes up, they'll still have power even if we attempt to remove it.

We need a way to exclude/include participants entirely.

**Comment by Kubuxu** [comment]
Ahh, I thought the power table delta just straight-up provided a new value for a given power, but from your comment, I'm guessing it is a difference in power.
