### ISSUE TITLE
F3 protocol version in manifest 

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#478]
The aim is to prevent the participation of people who didn't update.
This will allow us to deploy a rolling update during the testing phase in nv23

**Comment by Kubuxu** [comment]
It is a backup policy.
In essence, we would include a new backwards-compatible version of f3 in Lotus. Then we can deploy a new manifest to judge how many miners have upgraded and if there are enough of them for a good test, run the test enforcing the protocol version.

**Comment by jennijuju** [comment]
> It is a backup policy. In essence, we would include a new backwards-compatible version of f3 in Lotus. Then we can deploy a new manifest to judge how many miners have upgraded and if there are enough of them for a good test, run the test enforcing the protocol version.

Oh I see - thanks.
