### ISSUE TITLE
Create a message selector interface to avoid oligopolies in justification

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/go-f3#49]
The optimal aggregation of messages for #48 involves sorting the messages by voting power and then aggregating until the strong quorum is reached. This forms an oligopoly: the voters with the most power are always favoured over the voters with less power. Discuss the creation of an interface that allows the participant to select the selector mechanism it prefers to select messages to aggregate into a justification, so that the trade-off between democracy and performance is easily customizable on the client-side.  

This is probably most critical when implementing rewards for participation, if these rewards are based on reputation from participation or directly on whether the sender's message takes part of an aggregated signature.

**Comment by ranchalp** [comment]
If we do not have incentives in the end this is probably not necessary at all and we can just favour participants with most power when creating justifications.

**Comment by anorth** [comment]
With no reward incentives planned, I think we can close this for now. We can re-open if the FIP changes significantly.
