### ISSUE TITLE
Caching in message validation

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#527]
- [ ] Drop equivocations before validation because they cannot be useful. Unfortunately, we'd need access to equivocation state.
- [x] Potentially cache valid/invalid messages. Unclear how useful this is, it only helps with rebroadcast.
- [ ] ~Cache merkle-tree hashes.~ not an issue in practice
- [ ] Split pubsub message IDs into "validation IDs" and "propagation IDs"
    - At the validation layer, use the message hash to deduplicate (make sure to make this work with rebroadcast).
    - After successful validation, identify the message based on the hash of the gpbft _value_.
    - Only propagate messages with unique GPBFT values.

**Comment by masih** [comment]
> Drop equivocations before validation because they cannot be useful. 

I think gpbft should do this as an initial check prior to validation.

> Potentially cache valid/invalid messages. Unclear how useful this is, it only helps with rebroadcast.

Agreed. We should measure time spent on validation on the mainnet before actioning this bad boy.

**Comment by rjan90** [comment]
> Agreed. We should measure time spent on validation on the mainnet before actioning this bad boy.

@masih Do we have some metrics to see if this is worth prioritising before mainnet launch?

**Comment by masih** [comment]
>>>Potentially cache valid/invalid messages. Unclear how useful this is, it only helps with rebroadcast.

>>Agreed. We should measure time spent on validation on the mainnet before actioning this bad boy.

> Do we have some metrics to see if this is worth prioritising before mainnet launch?

Yes. This has [been measured](https://github.com/filecoin-project/go-f3/blob/1d172089fb6d2a10986a13c7037a6ae648ecbe57/metrics.go#L91), and [caching already implemented](https://github.com/filecoin-project/go-f3/blob/main/gpbft/participant.go#L57).

**Comment by masih** [comment]
@rjan90 In terms of ticket management, I recommend breaking this issue up into multiple ones captured in this repo, plus an additional issue at libp2p pubsub repo for the last issue (the f3 part would be integrating with the right hooks once the actual feature is implemented in pubusub).

**Comment by Stebalien** [comment]
Broken into:

- https://github.com/filecoin-project/go-f3/issues/602
- https://github.com/filecoin-project/go-f3/issues/601
