### ISSUE TITLE
Handle rebroadcast & pubsub falling behind

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#549]
When we get a rebroadcast storm, pubsub can fall behind which can make the issue worse. We should:

- [ ] Ideally introduce some kind of staggering to rebroadcast.
- [ ] Possibly increase pubsub buffer sizes.
- [ ] Possibly rate-limit rebroadcast.
- [ ] Optimize _what_ we rebroadcast.

**Comment by masih** [comment]
> Optimize what we rebroadcast.

We do broadcast more than what the FIP dictates: all messages except quality from the latest 2 rounds, unless we are in DECIDE phase. In which case, only DECIDE. 
What FIP demands depends on phase, and If I have not missed anything it _could_ be 2 messages less. Hence the simpler approach in implementation.

I suspect a more pressing issue is synchronised rebroadcast across nodes.

**Comment by Stebalien** [comment]
> I suspect a more pressing issue is synchronised rebroadcast across nodes.

That will help us avoid this situation, but won't solve it if we do get into this situation.

**Comment by rjan90** [comment]
@Stebalien What are the minimal things we need to implement here, so that in case of a severity where pubsub can falls behind, it does not cause any issues in the network?

**Comment by Stebalien** [comment]
We should:

1. Optimize what we rebroadcast.
2. Stagger rebroadcast (i.e., have all nodes add a random delay to their rebroadcast timeout).

**Comment by Stebalien** [comment]
We've:

1. Staggered rebroadcast.
2. Prioritized rebroadcasting newer messages.

I'm going to call this "done enough".
