### ISSUE TITLE
Detect self equivocation and self-censor

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#567]
If an SP runs multiple lotus nodes, these nodes may end up equivocating. We should be able to detect this pretty quickly in F3 and censor ourselves. We probably want:

1. GPBFT to indicate that it has seen an equivocating message from some specific participant.
2. The client integration to watch this stream for keys it's responsible for. If it sees one, we should either bow out entirely or detect if we should continue/stop based on our peer ID? Maybe?

**Comment by Kubuxu** [comment]
WAL will facilitate the knowledge of the messages we send. It could trigger tracking of IDs for which we participate. Not sure what should be the strategy when we detect it but I will think about it.

**Comment by Stebalien** [comment]
I don't think we need WAL for this. We _know_ the identities we're signing for.

**Comment by Stebalien** [comment]
Discussed sync:

1. We may not catch all equivocations in GPBFT itself, need to check this.
2. We can't _just_ use the WAL + pubsub because we won't propagate equivocations(?).

Hm. The fact that we don't propagate them is actually a bit of an issue... really, the best answer here is to find a better way to avoid equivocations in the first place.

**Comment by Stebalien** [comment]
Kind of a dumb solution but we _could_ use pubsub for this by broadcasting our leases (likely on a different channel). That would "solve" this issue, albeit at the cost of sending a message to literally everyone (not a huge deal, TBH).

**Comment by Kubuxu** [comment]
It also reveals the pubsub <-> minerID mapping which is not that great

**Comment by rjan90** [comment]
The integration of WAL: https://github.com/filecoin-project/go-f3/issues/392 will complete this ticket.
