### ISSUE TITLE
Avoid dropping decides from the previous instance

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#579]
We currently drop all messages from the previous instance, but we should consider allowing decides through. Otherwise, some nodes may not be able to make progress until they can use the certificate exchange.

**Comment by masih** [comment]
> until they can use the certificate exchange

So far the assumption (at least in my head) has been: that's what cert exchange protocol is for.

What is your take on latency if nodes solely rely on cert cert exchange to catch up?
What other things do you see going wrong if we do solely rely on cert exchange for node catch-up?

**Comment by Stebalien** [comment]
> What is your take on latency if nodes solely rely on cert cert exchange to catch up?

At the moment, we'll catch up pretty fast. But:

1. We can be as much as a full instance behind (we try to predict the interval, not necessarily the exact instant where a decision will be made).
2. I want to change the protocol to only attempt to catch-up when we fall 2 instances behind if we believe we'll receive the decision from GPBFT. Right now, the certificate exchange is an unnecessary waste of bandwidth most of the time.
