### ISSUE TITLE
Make F3 consensus final

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#603]
We need to:

1. Set a checkpoint (in the client) whenever we reach an F3 decision.
2. If we get a chain with an invalid base from lotus, we should wait a bit and try again rather than complaining loudly. I believe this should currently "work", but we'll likely have some noisy log messages.

**Comment by masih** [comment]
> If we get a chain with an invalid base from lotus, we should wait a bit and try again rather than complaining loudly. I believe this should currently "work", but we'll likely have some noisy log messages.

@Stebalien is this not already covered by:
1. [collectChain](https://github.com/filecoin-project/go-f3/blob/3f40360201135dbe92035148e90ee4a1e65d2b89/host.go#L417) returning nil if there is a divergence, which will cause [base with empty suffix](https://github.com/filecoin-project/go-f3/blob/3f40360201135dbe92035148e90ee4a1e65d2b89/host.go#L517) to be proposed as the next instance chain, plus
2. backoff at [computeNextInstanceStart](https://github.com/filecoin-project/go-f3/blob/3f40360201135dbe92035148e90ee4a1e65d2b89/host.go#L245), which will increase on base finalisation

?

**Comment by Stebalien** [comment]
Yeah, it _sounds_ like that part works.

**Comment by masih** [comment]
This is done when the Lotus PR gets merged. Currently in review.
