### ISSUE TITLE
Accessing potentially empty slice.

### ISSUE THREAD

**Issue by ruseinov** [filecoin-project/go-f3#643]
Should there be `is_empty` check? e.g. `if c.isZero() { return nil } `? Otherwise this will panic:
https://github.com/filecoin-project/go-f3/blob/2c6f7bf80f19398f97318599ae90c97e5291c47e/gpbft/chain.go#L143

The same goes for https://github.com/filecoin-project/go-f3/blob/bc35325b79c328949d4a7c22e8133a7d1cc5ee64/gpbft/chain.go#L176 and perhaps some other occurrences.

**Comment by Stebalien** [comment]
I guess we could return `nil` in these cases, but that would just move the panic elsewhere. Better documentation is likely in-order, these functions should only be called on non-zero chains.

**Comment by ruseinov** [comment]
> I guess we could return `nil` in these cases, but that would just move the panic elsewhere. Better documentation is likely in-order, these functions should only be called on non-zero chains.

Right, I'm combing through a lot of this code now as I'm working on the Rust implementation and trying to organize the API so that it's panic-free, propagating errors all the way to wherever they need to be handled or finally turned into a panic. I can appreciate that it might not be as ergonomic to do here.
