### ISSUE TITLE
Implement Synchronization of participants in the current instance

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/go-f3#69]
From [FIP](https://github.com/filecoin-project/go-f3/issues/68): 

"GossiPBFT ensures termination provided that (i) all participants start the instance at most $\Delta$ apart, and (ii) the estimate on Δ is large enough for $\Delta$-synchrony in some round (either because of the real network delay recovering from asynchrony or because of the estimate increasing).

[Given prior tests performed on GossipSub](https://research.protocol.ai/publications/gossipsub-v1.1-evaluation-report/vyzovitis2020.pdf) (see also [here](https://gist.github.com/jsoares/9ce4c0ba6ebcfd2afa8f8993890e2d98)), we expect that almost all participants will reach sent messages within $Δ=3s$, with a huge majority receiving them even after $Δ=2s$. However, if several participants start the instance $Δ + ε$ after some other participants, termination is not guaranteed for the selected timeouts of $2*Δ$. Thus, we do not rely on an explicit synchrony bound for correctness. Instead, we (i) use drand as a beacon to synchronize participants within an instance and (ii) increase the estimate of Δ locally within an instance as rounds progress without decision.

The synchronization of participants is performed in the call to updateTimeout(timeout, round) (line 47), and works as follows:

* Participants start an instance with $Δ=2s$.
* If the first and second rounds fail to reach termination, participants start the 3rd round with $Δ=3s$.
* If 5 rounds fail to reach termination (rounds from 0 to 4), participants wait to receive the next drand epoch value to start round 5. This ensures that a potential ε delay between when participants started the instance is not carried over beyond round 4.
* If round 5 fails to reach a decision, participants set exponential timeout increase $Δ= 1.3*Δ$ for every failed round. This ensures termination even if the real network delay increases arbitrarily."

**Comment by anorth** [comment]
I think we can do this without introducing a dependency on the external drand. Can we just use the clock time instead?

**Comment by ranchalp** [comment]
You are right. Using the network clock and assuming clocks synchronized better than whatever delta delay the network may have bee carrying then we do not need to rely on drand. See #81

**Comment by ranchalp** [comment]
As discussed on slack, we will for now go with only the exponential backoff applied from round 1. A future improvement was outlined however: 

> 
A way in which the clock tick always makes things only better or the same is if nodes signal (with a message) which clock tick in particular they use every X-th round. Then, when a node reaches its own time to calculate its clock tick at round X, it waits for its own clock tick as timeout unless it receives t+1 (i.e. a weak quorum of) clock ticks for round X from other nodes such that the t+1-th greatest clock tick is smaller than its own locally calculated clock tick (in which case it updates its timeout, and probably it immediately stops waiting). This ensures things do not get worse by the clock tick (easy to prove, as t+1-th greatest ensures an honest node sent a clock tick of the same value or lower), but it also is more complex to implement (involving a new message or a new field in the CONVERGE message). We should not have any clock tick (ntp drand or sth else) at all unless we have a mechanism like this one.
