### ISSUE TITLE
Limit WAL instances within WAL and enforce on hydration

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#693]
Stored WAL instances are limited to 5 by calls from runner start loop. 

If for whatever reason runner is interrupted repeatedly before purge is called or the WAL directory has more than 5 WAL files the current implementation reads them all on hydration.

Change the implementation such that this cannot happen by enforcing the maximum number of epochs within WAL itself, may it be applied as WAL rotates or during hydration.

**Comment by masih** [comment]
Kicking this out of milestone 2 as it is non-critical: for this to happen there needs to be a string of errors and even then a single progress of instance would wipe the prior data.

**Comment by Kubuxu** [comment]
IMO non-issue as any Purge call will clean up older instances. Closing.
