### ISSUE TITLE
Network message monitoring and collection

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#712]
Set up network message monitoring and collection for the purpose of post-factum analysis and metric collection.
Current idea is based on the parquet data format, `f3 observe` command and duckdb for parquet processing.
 - `f3 observe` to collect messages
 - maybe improve `f3 observe` to include message validation
 - periodically upload the parquet files to S3
 - build a script to download parquet files for time range, compact and optimize them to ease analysis

**Comment by masih** [comment]
Done in #744

**Comment by BigLep** [comment]
Handled by https://github.com/filecoin-project/go-f3/pull/744
Followup happening in https://github.com/filecoin-project/go-f3/issues/745
