### ISSUE TITLE
Fix participation loop so the miner re-joins if lotus restarts

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#719]
Currently, if the lotus node restarts and the F3 network does not make progress beyond the leased instance, the miner won't participate.

**Comment by Stebalien** [comment]
Ok, I've tried a few fixes here and I _think_ the right answer is to:

1. Remove the calls to `F3GetManifest` and `F3GetProgress`.
2. Add a `RecheckAt` field to the lease telling the miner when to check the lease. This is optional, but it means we don't need to grab the manifest to compute when we should check again. Alternatively, we can grab the manifest once every time the network changes?
3. At that time, call `F3Participate` again.
4. The lease returned by `F3Participate` specifies the _current_ instance along with the remaining number of instances for which the lease is valid. If this remaining number is less than half the initial lease term, the miner gets a new lease.
