### ISSUE TITLE
GetBestMiningCandidate & F3

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#730]
When we pick a base on which to mine, [we compare](https://github.com/filecoin-project/lotus/blob/2b7f595fa514a5bf3ec833ab06c45c44f38be951/miner/miner.go#L408-L439):

1. The current chain head.
2. The last tipset we mined on.

If the last tipset we mined on is heavier, we'll stick with that. This leads to a problematic situation:

1. We try mining on X.
2. F3 finalizes Y at the same height, Y is _lighter_ than X.
3. We will _keep_ trying to mine on X until someone else mines a block on Y.

- One option here is to remove the `lastWork` field, I'm not 100% sure why we have it. 
- Another is to change `ChainTipSetWeight` to take checkpoints into account and set the weight to 0 for any tipset not compatible with the current checkpoint. We need to be careful here in case the tipset weight is used anywhere else, but I don't _think_ it is?
- The best option is probably just to _ask_ lotus about the current checkpoint.

**Comment by Stebalien** [comment]
Note: I have no idea if this is _actually_ the issue, but it's very suspicious.

**Comment by Kubuxu** [comment]
I'm pretty certain the reason is catchup mining, where we fast loop and lotus takes too long to update the head.

**Comment by Stebalien** [comment]
Ok, I'm pretty sure there's no point behind `lastWork`. It's _only_ useful if lotus returns a block that's weighs less than the last block it returned. I guess maybe it's to solve the issue of lotus crashing, restarting, and... coming up with a worse block? I'm not convinced.

To be clear, `lastWork` literally just returns the best block we've seen from `ChainHead`. We don't update it anywhere except in `GetBestMiningCandidate`.

**Comment by Stebalien** [comment]
Oh! Maybe the concern is multiple lotus nodes where one is behind? I mean, this isn't really the right way to deal with that especially because we _completely ignore_ anything we mined.

**Comment by Stebalien** [comment]
It looks like we keep it for side effects in some cases... E.g., we shove the null rounds it it.

**Comment by Stebalien** [comment]
Ok, there's a simple fix: we can't mine at the same height anyways. So we'll just track the last height we've successfully determined we didn't win and use that to calculate nulls.

**Comment by Kubuxu** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/12690
