### ISSUE TITLE
Have a canonical way to take a FakeEC and build certs from it and/or compare that certs are corresponding to given chain

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#743]
Would prevent the bug in OhShitStore.
Provide a way to form certs from FakeEC and/or compare FakeEC with external certs.
Provides an extra assertion for testing GPBFT correctness (which we don't really do right now a lot) as well probably simplifies some tests (provide certs to nodes instead of running GPBFT).

**Comment by rjan90** [comment]
Test case for the bug that was hit on Calibration. Hope to have that done by 2024-11-20
