### ISSUE TITLE
Fix checkpoint sync in Lotus and merge mining test

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#746]
https://github.com/filecoin-project/lotus/pull/12659

The lastWork part was merge but tests identified deficiencies in sync when checkpoints are in play.

**Comment by BigLep** [comment]
@Kubuxu : this fixed by https://github.com/filecoin-project/lotus/pull/12747 right?

**Comment by Kubuxu** [comment]
Yes, it is fixed in it, although the mining test is not there.

**Comment by BigLep** [comment]
@Kubuxu is opening a new issue in Lotus

**Comment by Kubuxu** [comment]
https://github.com/filecoin-project/lotus/issues/12755
