### ISSUE TITLE
Make a public F3 grafana dashboard

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#747]
Now that F3 is active and progressing on calibration net create a public dashboard of metrics collected from nodes run by us for the benefit of the community. The dashboard should show:
* bandwidth usage
* CPU/Memory usage
* Disk space consumed by F3
* Internal F3 metrics
  * epochs finalized per instance
  * current instance 
  * cet exchange polling metics
  * time spent on validation
  * time spent on committee fetch 
  * cache growth

Note that the existing dashboards need to be refined in order to be made public: the parameterised dashboards cannot be made public. Therefore, we need to create new dashboards with fixed query criteria

**Comment by masih** [comment]
I have created a copy of the private dashboard and removed the query parameters so that it can be made public.

**Comment by rjan90** [comment]
Closing this ticket as the dashboard has been made public here: https://grafana.f3.eng.filoz.org/public-dashboards/396bb90ae6b942dcb40c7b4258933e1c.
