### ISSUE TITLE
Investigate `subscriber too slow` errors in pubsub

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#759]
Observed in passive testing on mainnet for `filecoin/16` network:

```
{"level":"info","ts":"2024-11-28T21:17:37.595+1100","logger":"pubsub","caller":"go-libp2p-pubsub@v0.11.0/pubsub.go:981","msg":"Can't deliver message to subscription for topic /f3/granite/0.0.2/filecoin/16; subscriber too slow"}
{"level":"info","ts":"2024-11-28T21:17:37.595+1100","logger":"pubsub","caller":"go-libp2p-pubsub@v0.11.0/pubsub.go:981","msg":"Can't deliver message to subscription for topic /f3/granite/0.0.2/filecoin/16; subscriber too slow"}
{"level":"info","ts":"2024-11-28T21:17:37.595+1100","logger":"pubsub","caller":"go-libp2p-pubsub@v0.11.0/pubsub.go:981","msg":"Can't deliver message to subscription for topic /f3/granite/0.0.2/filecoin/16; subscriber too slow"}
```

This indicates that the processing loop is taking too long to process received messages. 
`ida` metrics at the corresponding time interval in which this occured: https://grafana.f3.eng.filoz.org/d/edsu1k5s7gtfkb/f3-passive-testing?orgId=1&var-network=mainnet&var-instance=ida.f3.eng.filoz.org:80&from=1732789053994&to=1732789928949&tab=transform

**Comment by masih** [comment]
We should set Tracer in pubsub and log `UndeliverableMessage`; such messages end up in that tracer call.

**Comment by masih** [comment]
The buffer size of 20 [here](https://github.com/filecoin-project/go-f3/blob/6b6b5c51dd183022e0fd6e91d2c08043e61c7db3/host.go#L561) may be too small for large networks.

**Comment by masih** [comment]
With buffer sizes bumped to 512 both for internal buffer size and pubsub subscriber buffer size seem to have fixed the issue at network scale of 40%.

The true fix is to make the processing loop faster, or internally buffer messages in a more sophisticated way inside GPBFT (and indeally hook it up to validation/internal state to drop messages early if they are not processed yet , were valid when buffered, and became useless)

**Comment by masih** [comment]
There is a flurry of these messages every time we re-bootstrap a passive testing network. 

I believe the cause could also be that the gpbft runner gets paused when manifest changes and resumes again close to bootstrap of the new manifest. The runner is where the consume loop of topic subscription lives.  Meaning, when paused no messages from the previous network topic gets consumed, and hence the "queue full" error.

If on archioz we also only observe this error during rebootstrap then I believe this is a non-issue. Though will not hurt to bump the limits anyway.

**Comment by masih** [comment]
Observed subscriber too slow error flurry on `ida` _just_ before instance 4 started in network `filecoin/40`.

**Comment by Kubuxu** [comment]
@masih was ida at the time running with the buffer patch or not?

**Comment by masih** [comment]
> running with the buffer patch or not?

No but archioz was

**Comment by masih** [comment]
OK looks like archioz is running the commit [that doesn't have the buffer bump](https://github.com/filecoin-project/lotus/commit/e7b7ce163). And it _did_ observer the subscriber too slow. 

Interestingly, a lot more than ida did.

**Comment by masih** [comment]
New observation: On both ida and archioz when this happens committee fetch time is at its max: 2-3 seconds. 

It seem likely that slow committee fetch can cause this. Which brings me to ask why get committee times are shooting up

<img width="352" alt="image" src="https://github.com/user-attachments/assets/5e6827f6-5955-4c84-916a-f3f60895c56a">

**Comment by masih** [comment]
resolved by https://github.com/filecoin-project/go-f3/issues/779
