### ISSUE TITLE
Make maximum chain length configurable in manifest

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#772]
F3 implementation has a hard limit on chain length: 100 tipsets. This limit is baked into the code in several places. This limit is also hit every time the network bootstraps for at least 9 times (due to 900 epoch lookback at bootstrap time).

One of the key factors affecting the bandwidth usage of F3, specially during catch up/bootstrap, is the size of the messages which is currently heavily influenced by the chain length. 

Ideally, we want to make the 100 length configurable in the manifest so that we can experiment with different configurations to see impact on bandwidth usage during catch up.

**Comment by masih** [comment]
Approach suggestion:

Keep the max chain length constant as 100.

Update host `GetProposal` to optionally apply a max that comes from Manifest, with fallback to constant ( and constant max enforced regardless) here:

https://github.com/filecoin-project/go-f3/blob/fb028a4bbb45af164ae49ab326c34f037f72b88c/host.go#L726


I _think_ that should do it.

**Comment by Kubuxu** [comment]
Yes, that would do it.

**Comment by masih** [comment]
Note, max was increased to 128, because:

https://github.com/filecoin-project/go-f3/pull/788#discussion_r1880536298
