### ISSUE TITLE
GetProposal and GetCommittee too slow

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#779]
Observing high get committee times which in turn increases get proposal times on ida and archioz:

Most likely this is the root cause of #759 

https://github.com/filecoin-project/go-f3/blob/0a6bda4ca2a3bd922c82581f86de8b4b805ce9b0/host.go#L720-L742

**Comment by masih** [comment]
@Kubuxu On both archioz and ida, between 1250 until network change (1500 ish) the committee fetch time was very high. 

**But** not before it. Network bootstrapped at 0845.

In the entire time F3 was at least 700 epochs behind head.

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/6c74db43-d0bb-49cc-850b-23685956cb94">

**Comment by masih** [comment]
In `filecoin/42` network, i observe high _proposal fetch time_, which coincides with "subscriber too slow" errors. I understand both slow committee fetch and proposal fetch are related.

I'd like to point out that at instance start slow proposal fetch causes more harm: can knock instance starts out of balance, resulting in poor propagation of QUALITY messages which then leads to prepare for base, additional rounds and if we are lucky decide on non-base.

**Comment by Stebalien** [comment]
Note: I get the feeling we can also do this in parallel to get a significant speedup, at least during bootstrap.

**Comment by masih** [comment]
> I get the feeling we can also do this in parallel to get a significant speedup

Get power table per tipset can indeed be pararellised though I don't know if they end up hitting the same mutex deep inside lotus or not.

The call to get proposal cannot. It's called exactly once in go-f3 just before instance start in any case.

What also seems to be a low hanging fruit is _repeated calls to get power table for the same tipset_, which I believe Kuba is working on to cache.

**Comment by Stebalien** [comment]
Oh, I see....

**Comment by Kubuxu** [comment]
https://github.com/filecoin-project/lotus/pull/12770
https://github.com/filecoin-project/go-f3/pull/784

**Comment by masih** [comment]
Closing as the chaching and state load improvements are merged. I think we expect the operation to be at least 30% faster? 
Closing for now and will reopen later if further improvement is needed.
