### ISSUE TITLE
Get proposal metrics on dashboard look incorrect

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-f3#780]
The get proposal times on the dashboard look incorrect relative to 99th percentile. 

<img width="403" alt="image" src="https://github.com/user-attachments/assets/6c561c79-9c8d-4538-aa48-b6a54ed6f41f">

**Comment by Kubuxu** [comment]
The average metric is correct, the histogram buckets cap out on 5s, so it is unable to estimate higher than that.

**Comment by masih** [comment]
Thanks Kuba in which case we need explicit bucket config
