### ISSUE TITLE
Handling worker key reuse

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#98]
Right now, unless I'm mistaken, SPs can reuse the same worker key across multiple miner actors. We likely need to handle this...

The upside is that this may let us aggregate power across multiple miner actors...

**Comment by Stebalien** [comment]
@Kubuxu I assume this is an issue for aggregation?

**Comment by Kubuxu** [comment]
I don't think it is; in general, aggregation does not care about it. We also use a scheme that is resistant to rouge key attacks which would prevent from affecting it even further.
